config/routes.rb
AddLive::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients
  resources :client
  resources :ads
  resources :pin
  devise_for :users
  resources :clicks
  
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  get "users/new"

  root :to => 'staticpage#index'
  match '/vision', to: 'staticpage#vision'
  match '/about', to: 'staticpage#about'
  match '/career', to: 'staticpage#career'
  match '/rewards', to: 'staticpage#faq'
  match '/plan', to: 'staticpage#plan'
  match '/support', to: 'staticpage#support'
  match '/whyaddlive', to: 'staticpage#whyaddlive'
  match '/statistics', to: 'staticpage#statistics'
  match '/ads/index', to: 'ads#index'
  match '/workdesk/ads_list', to: 'workdesk#ads_list'
  match '/ads/:id', to: 'ads#show'
  match '/searchyourneed', to: 'staticpage#need'
  match '/signup', to: 'users#new'
  match '/Workdesk', to: 'Workdesk#index'
  match '/client', to: 'client#index'
  match '/check', to: 'ads#check'
  match '/fail', to: 'ads#fail'
  match '/success', to: 'ads#success'
  match '/career_page/:id', to: 'staticpage#career_page'
  match '/full_ads/:id', to: 'client#full_ads'
  match '/workdesk/create_request', to: 'workdesk#create_request'
  match 'workdesk/paid_history', to: 'workdesk#paid_history'
  match '/users', to: 'users#edit'
  match '/update', to: 'users#update'
  match '/legal', to: 'staticpage#legal'
  

  

end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController

	
def index
	@ads1=Ads.where(:Imageslide => true).all(:order => "rand()")
	@search_need = Need.all
	@roles=Ads.all
	@users = User.all	
	@clients= Client.all
	@ads= Ads.all
	@careers= Career.all
	@clicks=Clicks.all
end

def statistics
	
end

def need
	@selected_city = params[:city_search]
	@selected_category = params[:category_search]	

	@needs= Need.where(:city => @selected_city, :category => @selected_category)
	
end


	
def career
	@career = Career.all(:order => '(created_at) DESC')
end

def career_page
	@career1=Career.find(params[:id])
end

def side_bar

end



end

app/helpers/staticpage_helper.rb
module StaticpageHelper
	
	def ppt_path(file)
  		File.join('/download', file).to_s
	end
end

app/views/staticpage/_search_result.html.erb
<ul>
  <% @search_need.each do |i| %>
  <li><%= i.city %></li>
  <li><%= i.category %></li>
  <% end %>
</ul>

app/views/staticpage/career.html.erb
<%=provide(:title, 'Career') %>
<div class="index_page">
	<div class="container">	
		<div class="span12">
			<div class="title_tag">
				<%=image_tag("title241x40.png") %>
			</div>
			<div class="title_line">
				<%=yield(:title) %>
			</div>
			<div class="workdesk_parts">
				<div class="heading_lable1"><%=image_tag("AddLiveCareer copy3.jpg") %></div>
				<% @career_count =1 %>
				<table class="table table-bordered">
					<tr>
						<th> # </th>
						<th> Company </th>
						<th> Job profile </th>
						<th> Eligbility </th>
						<th> Posting Date </th>
						<th> more info </th>
					</tr>

					<% for i in @career %>
					<tr>
						<td><%= @career_count%> <% @career_count +=1 %></td>
						<td><%= i.company %></td> 
						<td><%= i.jobprofile %></td>
						<td><%= i.eligbility %></td>
						<td><%= i.created_at.strftime("%d %b. %Y") %></td>
						<td><%= link_to "Click here...",:action => "career_page",:id => i.id %></td>
					</tr>
					<% end %>
	  
				</table>
			</div>





		</div>
	</div>
</div>

app/views/staticpage/career_page.html.erb
<%=provide(:title, "job page") %>
<div class="index_page">
	<div class="container">	
		<div class="span12">
			<div class="title_tag">
				<%=image_tag("title241x40.png") %>
			</div>
			<div class="title_line">
				<%=yield(:title) %>
			</div>
			<div class="span8 offset2">
				<div class="workdesk_parts career_data">
					<table cellpadding="10">
						<tr>
							<td>Company Name</td><td>:</td>
							<td><%= @career1.company %></td>
						</tr>
						<tr>
							<td>Job profile</td><td>:</td>
							<td><%= @career1.jobprofile %></td>
						</tr>
						<tr>	
							<td>Eligbility</td><td>:</td>
							<td><%= @career1.eligbility %></td>
						</tr>
						<tr>
							<td>Contact Person</td><td>:</td>
							<td><%= @career1.contactperson %></td>
						</tr>
						<tr>
							<td>Address</td><td>:</td>
							<td><%= @career1.address %></td>
						</tr>
						<tr>
							<td>Contact number</td><td>:</td>
							<td><%= @career1.contactno %></td>
						</tr>
						<tr>
							<td>Posting Date</td><td>:</td>
							<td><%= @career1.created_at.strftime("%d %b. %Y") %></td>
						</tr>
						<tr>
							<td>Remark</td><td>:</td>
							<td><%= @career1.remark %></td>
						</tr>
					</table>
				</div>
			</div>		
		</div>
	</div>
</div>

app/views/staticpage/faq.html.haml
=provide(:title, 'Rewards')
%title
	= yield(:title)
.index_page
	.container
		.span8
			.title_tag
				=image_tag("title241x40.png")
			.title_line
				Rewards
			.page_data
				.heading_lable
					=image_tag("add-live.jpg")
				.coming
					Coming Soon ......
		.span4
			= render :template => "staticpage/side_bar"

app/views/staticpage/intro.html.erb
<div id="content">
<div class="single-shadow">
  <h2>  </h2>
  <div id="ticker">
    <div>
      <h2>Welcome to Add-Live</h2>
      <h5>Where ads add happiness</h5>
        <p><ul><li>Now you can Add more earnings by Watching Advertisements.<li>Advertiser can pramote their products to help increase sales.<li>Add-Live is one of the best environment for Advertisements.<li>Follow 3 easy steps to grow your business over internet.</ul></p><br \>
        <a class="next" href="#">Go to Step # 1</a>
    </div>
    <div>
      <h3>Step 1.</h3>
        <ul>
            <li>Members, can watch the Advertisements and get paid for it.</li>
            <li>Advertiser, can promote their products over internet through Add-Live. </li>
        </ul>
        <a class="next" href="#">Go to Step # 2</a>
    </div>
    <div>
        <h3>Step 2.</h3>
        <p>Register Your Self.<ul><li>Advertiser can register by simply sending an e-mail with fields like e-mail, name, address, contact no, city and category.<li>Member can register by clicking on registration button, member can get their joinging pin by any of the franchise.</ul></p>
        
        <a class="next" href="#">Go to Step # 3</a>
    </div>
    <div>
        <h3>Step 3.</h3>
        <ul>
            <li>Members can login into member section and get paid by watching Advertisements.</li>
            <li>Advertiser can login into Advertiser section and get update about their Advertisements like total clicks, no of Advertisements viewed, no of clicks remain.</li>
        </ul>
        <a class="next" href="#">Restart</a>
    </div>
    
  </div>
 </div> 
</div>




app/views/staticpage/legal.html.haml
=provide(:title, 'Legal')
%title
	= yield(:title)
.index_page
	.container
		.span8
			.title_tag
				=image_tag("title241x40.png")
			.title_line
				Legal
			.page_data
				.heading_lable
					=image_tag("add-live.jpg")
				.coming
					Coming Soon ......
		.span4
			= render :template => "staticpage/side_bar"

app/views/staticpage/need.html.erb
<%=provide(:title, 'Your Needs') %>
<div class="index_page">
  <div class="container"> 
    <div class="span12">
      <div class="title_tag">
        <%=image_tag("title241x40.png") %>
      </div>
      <div class="title_line">
        <%=yield(:title) %>
      </div>
      <div class="workdesk_parts">
      
        <%= render :partial =>'staticpage/searchneed' %>
          <div class="span7 offset2">
            <% if @needs.blank? %>
              <div class="format_search_data2">
                No records Found.....
              </div>  
            <% else %>
              <% for need in @needs %>
              <table class="search_need_data">
                <tr>
                  <td><ul>
                    <li><div class="format_search_data"><b><font color="White"><%= need.orgname %></font></b></div> <div class="format_search_data1  ">
                    <table>

                  <tr><td><%= "Contact no" %></td><td>:  </td><td><%= need.contactno %></td></tr>
                  <tr><td><%= "Address" %></td><td>:  </td><td><%= need.address %></td></tr>
                  <tr><td><%= "category" %></td><td>:  </td><td><%= need.category %></td></tr>
                  <tr><td><%= "city" %></td><td>:  </td><td><%= need.city %></td></tr></table></li></ul></td></div>
                </tr>
              
              </table>
              <% end %>
            <% end %>
          </div>
      
      </div>
    </div>
  </div>
</div>

app/views/staticpage/plan.html.haml
=provide(:title, 'Plan')
%title
	= yield(:title)
.index_page
	.container
		.span8
			.title_tag
				=image_tag("title241x40.png")
			.title_line
				Our Plan
			.page_data
				.heading_lable
					=image_tag("add-live.jpg")
				.plan_data
					Download Add-Live Presentations:
				.presentation				
					%br
					=link_to "For Clients", ppt_path('ADD-LIVE FOR CLIENTS.ppsx')
					%br
					%br
					=link_to "For Members", ppt_path('ADD-LIVE FOR MEMBERS.ppsx')
		.span4
			= render :template => "staticpage/side_bar"

app/views/staticpage/side_bar.html.haml
.spa3
	.latest_news
		.latest_heading
			Latest News and Events
		.latest_data
			%marquee{:direction => "up", :scrollamount => 3}
				Welcome,
				%br
					Add-Live.com,
				%br
					A Place where ads-add happiness. 
				%br	 
					For any enquiry contact to support@add-live.com

	-if user_signed_in?
		.members_area
			%strong Welcome,
			.signup_button
				= current_user.fname
				= current_user.lname
		.members_area
			.signup_button
				=link_to "Go to Workdesk",'Workdesk#index'
	-else
		-if client_signed_in?
			.members_area
				%strong Welcome,
				.signup_button
					= current_client.fname
					= current_client.lname
			.members_area
				.signup_button
					=link_to "Go to Clientdesk",'client#index'
		-else
			%form 
				.members_area
					%strong Members Area
					%br
					.btn.btn-inverse.btn-primary.signup_button
						=link_to "Sign in Here",new_user_session_path

				.members_area
					%strong New user ?
					%br
					.btn.btn-inverse.btn-primary.signup_button
						=link_to "Click Here to Register", new_user_registration_path
					

				.members_area
					%strong Client Area  
					%br
					.btn.btn-inverse.btn-primary.signup_button
						=link_to "Sign in Here",new_client_session_path
	.members_area
		%strong Catch Add-Live on Facebook
	= render :template => "staticpage/social"
	




                 







                                                                

app/views/staticpage/social.html.erb
<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FAddLivecom&amp;width=292&amp;height=290&amp;show_faces=true&amp;colorscheme=light&amp;stream=false&amp;border_color=orange&amp;header=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:290px;" allowTransparency="true"></iframe>


app/views/staticpage/statistics.html.erb

<div class="statistics">
	<div class="container">	
		<div class="span9">
			<div class="title_tag">
				<%=image_tag("title241x40.png") %>
			</div>
			<div class="title_line">
				Statistics
			</div>
			<div class="span6 offset2">
			<div class="workdesk_parts">
				<label class="heading_lable">Company Statistics</label>
				<strong>
				<table class="table table-hover" cellpadding="10">
 	
				<tr><td width="200">Viewer</td><td><%= @users.count %></td></tr>
				<tr><td width="200">Clients</td><td><%= @clients.count %></td></tr>
				<tr><td width="200">Ads</td><td><%= @ads.count %></td></tr>
				<tr><td width="200">Total ad view</td><td><%= @clicks.count %></td></tr>
				<tr><td width="200">Jobs</td><td><%= @careers.count %></td></tr>
				<tr><td width="200">Total Page Visit</td><td><!-- BEGIN: Powered by Supercounters.com -->
				<script type="text/javascript" src="http://widget.supercounters.com/texthit.js"></script><script type="text/javascript">var sc_texthit_var = sc_texthit_var || [];sc_text_hit(507293,"Visits","170ddb");</script><br><noscript><a href="http://www.supercounters.com/">Free tumblr hit counter</a></noscript>

				<!-- END: Powered by Supercounters.com -->
				</td></tr>
				<tr><td width="200">Online User</td><td> <!-- BEGIN: Powered by Supercounters.com -->
				<script type="text/javascript" src="http://widget.supercounters.com/online_t.js"></script><script type="text/javascript">sc_online_t(507305,"Users Online","170ddb");</script><br><noscript><a href="http://www.supercounters.com/">Users Online Counter</a></noscript>

				<!-- END: Powered by Supercounters.com -->
				</td></tr>
				
				</table>
			</strong>
			</div>
			</div>
		</div>
	</div>
</div>

app/views/staticpage/support.html.erb
<%=provide(:title, 'Support') %>
<div class="index_page">
	<div class="container">	
		<div class="span9">
			<div class="title_tag">
				<%=image_tag("title241x40.png") %>
			</div>
			<div class="title_line">
				<%=yield(:title) %>
			</div>
			<div class="span6 offset2">
			<div class="workdesk_parts">
				<label class="heading_lable">Contact Person</label>

				<table class="table table-hover" >
					<tr><td><b>Name</b></td><td><b>City</b></td><td><b>Contact no</b></td></tr>
					<% for i in @support %>
					<tr><td><%= i.fname %></td>
						<td><%= i.city %></td> 
						<td><%= i.contactno %></td></tr>
					<% end %>
				</table>
			</strong>
			</div>
			</div>
		</div>
	</div>
</div>

app/views/staticpage/vision.html.haml
=provide(:title, 'Vision')
%title
	= yield(:title)
.index_page
	.container
		.span8
			.title_tag
				=image_tag("title241x40.png")
			.title_line
				Our Vision
			.page_data
				.heading_lable
					=image_tag("add-live.jpg")
				Our marketing team is a talented bunch. We care about our members, clients, our work and our Ads. 
				Become the biggest internet advertising agency in nation with high creativity, performance and customer services.
				

		.span4
			= render :template => "staticpage/side_bar"

app/views/staticpage/whyaddlive.html.haml
=provide(:title, 'Why Add-live')
%title
	= yield(:title)
.index_page
	.container
		.span8
			.title_tag
				=image_tag("title241x40.png")
			.title_line
				Why Add-Live
			.page_data
				.heading_lable
					=image_tag("add-live.jpg")
				%h3
					Why choose Add-Live,
				%p

				%p
					* Not only watching ads but also read, understand and analyze the product or service.
				%p
					* Focus on big as well as small business.
				%p
					* City wise distributed.
				%p
					* Less expensive
				%p
					* Fastest marketing
				%p
					* 100% Literate viewers
				%p
					* Direct reach to large no of local and global viewer.
				%p
					* Varity of ads (same products)
				%p
					* Online Viewer data
				%p
					* Online ads manegment
				%p
					* Free listing in classified for life time
				%p
					* Free job posting facility.
				%p
					* Automatic renewal.
				%p
					* Direct Coustomer reference.
				%p
					* Effective products/services rating.		
				%p
					* Your Need, Your choice
				%p
					* Effortless income
				%p
					* Work from your working area
		.span4
			= render :template => "staticpage/side_bar"