config/routes.rb
AddLive::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients
  resources :client
  resources :ads
  resources :pin
  devise_for :users
  resources :clicks
  
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  get "users/new"

  root :to => 'staticpage#index'
  match '/vision', to: 'staticpage#vision'
  match '/about', to: 'staticpage#about'
  match '/career', to: 'staticpage#career'
  match '/rewards', to: 'staticpage#faq'
  match '/plan', to: 'staticpage#plan'
  match '/support', to: 'staticpage#support'
  match '/whyaddlive', to: 'staticpage#whyaddlive'
  match '/statistics', to: 'staticpage#statistics'
  match '/ads/index', to: 'ads#index'
  match '/workdesk/ads_list', to: 'workdesk#ads_list'
  match '/ads/:id', to: 'ads#show'
  match '/searchyourneed', to: 'staticpage#need'
  match '/signup', to: 'users#new'
  match '/Workdesk', to: 'Workdesk#index'
  match '/client', to: 'client#index'
  match '/check', to: 'ads#check'
  match '/fail', to: 'ads#fail'
  match '/success', to: 'ads#success'
  match '/career_page/:id', to: 'staticpage#career_page'
  match '/full_ads/:id', to: 'client#full_ads'
  match '/workdesk/create_request', to: 'workdesk#create_request'
  match 'workdesk/paid_history', to: 'workdesk#paid_history'
  match '/users', to: 'users#edit'
  match '/update', to: 'users#update'
  match '/legal', to: 'staticpage#legal'
  

  

end

app/controllers/workdesk_controller.rb
class WorkdeskController < ApplicationController
	before_filter :authenticate_user!
	
	def index
		@count=1
		@user=current_user.fname
		@ref_points = 0
		$ads=Ads.find(:all, :order => "RAND()", :limit => 10)
		$refers=User.where(:sponserID => current_user.username)
		@pins= Pin.where("frenchisename=?",current_user.username)
		@total_ads_points=Points.where( :user_id => current_user.id, :Referal => false).sum :points
		@req_points =PaidReqPoints.where(:user_id => current_user.id, paid: [false,nil]).sum :points
		@paid_points =PaidReqPoints.where(:user_id => current_user.id, paid: [true]).sum :points
		@total_tds =PaidReqPoints.where(:user_id => current_user.id).sum :tds
		@total_admincharge =PaidReqPoints.where(:user_id => current_user.id).sum :admincharge
			

	end

	def create_request
		if current_user.panno ==""
			@tds = $balance_points*20/100
		else 
			@tds =$balance_points/10
		end
		@admin_charge = $balance_points/10
		@payable_balance_point = $balance_points - @admin_charge - @tds
		PaidReqPoints.create(:user_id => current_user.id, :paid => false , :points => @payable_balance_point, :tds => @tds, :admincharge => @admin_charge)
		redirect_to root_path
	end

	def paid_history
		@paid_history=PaidReqPoints.where("user_id=?",current_user.id)
	end


end

app/helpers/workdesk_helper.rb
module WorkdeskHelper
end

app/views/workdesk/ads_list.html.erb
<label class="heading_lable">Ads</label>

<table class="table table-hover" >
	<tr><td><b>Ads ID</b></td><td><b>Orgnization name</b></td><td><b>Question</b></td></tr>
	<% for i in $ads %>
		<% if i.totalclicks > i.usedclicks and i.Active == true and (i.city == current_user.city or i.city == "all") %>
			<tr><td><%= i.id %></td>
			<td><%= link_to i.orgname, :controller => :ads,:id => i.id %></td> 
			<td><%= i.que %></td></tr>
		<% end %>
	<% end %>
</table>

app/views/workdesk/earn.html.erb
<label class="heading_lable">Points Earn</label>


<% for i in $refers %>
	<% if i.packagetype == "Silver" %>
		<% @ref_points=@ref_points+100 %>
	<% end %>

	<% if i.packagetype == "Gold" %>
		<% @ref_points=@ref_points+200 %>
	<% end %>

	<% if i.packagetype == "Platinum" %>
		<% @ref_points=@ref_points+300 %>
	<% end %>
<% end %>
<table class="table">
	<tr>
	<td>
<%= "Total Ads Points" %></td><td>
<%= number_with_precision(@total_ads_points) %> 
	</td></tr>
	<tr>
	<td>
<%= "Total Referal points" %></td><td>
<%= @ref_points %>
	</td></tr>
	<tr>
	<td><strong>
<%= "Total Earned points" %></td><td>
<% @total_earned_points = @ref_points + @total_ads_points %>
<strong><%= number_with_precision(@total_earned_points) %>
	</td></tr>
	<tr>
	<td>
<%= "Paid Points" %></td><td>
<%= @paid_points %> 
<%if @paid_points > 1 %>
<div class ="req">
		<%= link_to "History", workdesk_paid_history_path %> </div><% end %>
	</td></tr>

	<tr>
	<td>
<strong><%= "Balance Points" %></td><td>
<% $balance_points = @total_earned_points - @paid_points-@total_tds-@total_admincharge - @req_points %> 
<strong><%= number_with_precision($balance_points) %> 
	<% if $balance_points >= 500 %> 
	<div class ="req">
		<%= link_to "Request", workdesk_create_request_path %> </div>
	<% end %>
	</td></tr>

	<tr>
	<td>
<%= "Request Points" %></td><td>
<%= @req_points %> 
	</td>
	</tr>
</table>

app/views/workdesk/home.html.erb
this is home page rendering

app/views/workdesk/index.html.erb
<%=provide(:title, 'My Workdesk') %>
<div class="index_page">
	<div class="container">	
		<div class="span9">
			<div class="title_tag">
				<%=image_tag("title241x40.png") %>
				
			</div>
			<div class="title_line">
				<%=yield(:title) %>
			</div>
			<% if current_user.frenchise == true %>

				<div class="workdesk_parts">	
					<div class="tabbable"> <!-- Only required for left/right tabs -->
					  <ul class="nav nav-tabs">
					    <li class="active"><a href="#tab1" data-toggle="tab">Ads</a></li>
					    <li><a href="#tab2" data-toggle="tab">Earning</a></li>
					    <li><a href="#tab3" data-toggle="tab">Referrals</a></li>
					    <li><a href="#tab4" data-toggle="tab">My Profile</a></li>
					    <li><a href="#tab5" data-toggle="tab">Used Pins</a></li>
					    <li><a href="#tab6" data-toggle="tab">Unused Pins</a></li>
					  </ul>

					  <div class="tab-content">
					    <div class="tab-pane active" id="tab1">
					      <%= render :template => 'workdesk/ads_list' %>
					    </div>
					    <div class="tab-pane" id="tab2">
					      <%= render :template => 'workdesk/earn' %>
					    </div>
					    <div class="tab-pane" id="tab3">
					      <%= render :template => 'workdesk/refer' %>
					    </div>
					    <div class="tab-pane" id="tab4">
					      <%= render :template => 'workdesk/profile' %>
					    </div>
					    <div class="tab-pane" id="tab5">
					       <%= render :template => 'workdesk/used_pin' %>
					    </div>
					    <div class="tab-pane" id="tab6">
					       <%= render :template => 'workdesk/unused_pin' %>
					    </div>

					  </div>
					</div>
				</div>

				
			<% else %>
				<div class="workdesk_parts">	
					<div class="tabbable"> <!-- Only required for left/right tabs -->
					  <ul class="nav nav-tabs">
					    <li class="active"><a href="#tab1" data-toggle="tab">Ads</a></li>
					    <li><a href="#tab2" data-toggle="tab">Earning</a></li>
					    <li><a href="#tab3" data-toggle="tab">Referrals</a></li>
					    <li><a href="#tab4" data-toggle="tab">My Profile</a></li>
					  </ul>

					  <div class="tab-content">
					    <div class="tab-pane active" id="tab1">
					      <%= render :template => 'workdesk/ads_list' %>
					    </div>
					    <div class="tab-pane" id="tab2">
					      <%= render :template => 'workdesk/earn' %>
					    </div>
					    <div class="tab-pane" id="tab3">
					      <%= render :template => 'workdesk/refer' %>
					    </div>
					    <div class="tab-pane" id="tab4">
					      <%= render :template => 'workdesk/profile' %>
					    </div>

					  </div>
					</div>
				</div>
			<% end %>

			
		</div>
	</div>
</div>

app/views/workdesk/paid_history.html.erb
<%=provide(:title, 'Paid History') %>
<div class="index_page">
	<div class="container">	
		<div class="span9">
			<div class="title_tag">
				<%=image_tag("title241x40.png") %>
			</div>
			<div class="title_line">
				<%=yield(:title) %>
			</div>
			<div class="span8 offset2">
			<div class="workdesk_parts">
				<label class="heading_lable">Paid History</label>

					<table class="table " >
						<tr>
							<td><b>Serial no</b></td>
							<td><b>Paid Points</b></td>
							<td><b>TDS</b></td>
							<td><b>Admin Charge</b></td>
							<td><b>Total Amount</b></td>
							<td><b>Paid Date</b></td>
						</tr>
						<% @count=1 %>
						<% for i in @paid_history %>
							<tr>
								<td><b><%= @count %></b></td>
								<td><%= i.points %></td>
								<td><%= i.tds %></td>
								<td><%= i.admincharge %></td>
								<td><%= i.points+i.tds+i.admincharge %></td>
								<td><%= i.PaidDate.strftime("%d %b. %Y") %></td> 
								
								<% @count=@count+1 %>
							</tr>
						<% end %>

							
					</table>

			</div>
			</div>
		</div>
	</div>
</div>



app/views/workdesk/profile.html.erb
<label class="heading_lable">My Profile</label>

<table class="table table-hover">
 <tr><td><strong>User name</strong></td>
 	<td><%= current_user.username %></td></tr>
 <tr><td><strong>Package Type</strong></td>
 	<td><%= current_user.packagetype %></td></tr>
 <tr><td><strong>First name</strong></td>
 	<td><%= current_user.fname %></td></tr>	
 <tr><td><strong>Last Name</strong></td>
 	<td><%= current_user.lname %></td></tr>
 <tr><td><strong>Email ID</strong></td>
 	<td><%= current_user.email %></td></tr>
 <tr><td><strong>Address</strong></td>
 	<td><%= current_user.address %></td></tr>
 <tr><td><strong>City</strong></td>
 	<td><%= current_user.city %></td></tr>
 <tr><td><strong>State</strong></td>
 	<td><%= current_user.state %></td></tr>
 <tr><td><strong>PIN code</strong></td>
 	<td><%= current_user.pincode %></td></tr>
 <tr><td><strong>Name of Bank</strong></td>
 	<td><%= current_user.nameofbank%></td></tr>
 <tr><td><strong>Account no.</strong></td>
 	<td><%= current_user.accountno %></td></tr>
 <tr><td><strong>IFSC code</strong></td>
 	<td><%= current_user.ifscno %></td></tr>
 <tr><td><strong>PAN no.</strong></td>
 	<td><%= current_user.panno %></td></tr>

<tr><td><%= link_to "Edit Profile",  'users#edit' %></td><td></td></tr>
</table>

	


app/views/workdesk/refer.html.erb
<label class="heading_lable">Refrals</label>

<table class="table table-hover" >
	<tr><td><b>Serial no</b></td><td><b>Name</b></td><td><b>User name</b></td><td><b>Joining Date</b></td><td><b>Package type</b></td></tr>
	<% for i in $refers %>
		<tr><td><b><%= @count %></b></td><td><%= i.fname %> <%= i.lname %></td>
		<td><%= i.username %></td> 
		<td><%= i.created_at.strftime("%d %b. %Y") %></td><td><%= i.packagetype %></td></tr>
		<% @count=@count+1 %>
	<% end %>
</table>

app/views/workdesk/unused_pin.html.erb
<label class="heading_lable">Unused Pins</label>

<table class="table table-hover" >
	<tr>
		<td><b>Serial no</b></td>
		<td><b>Joining pin</b></td>
		<td><b>package</b></td>
	</tr>
	<% @count=1 %>
	<% for i in @pins %>
	<% if i.frenchisename == current_user.username and i.used == false %>
		<tr>
			<td><b><%= @count %></b>
			</td><td><%= i.jpin %></td>
			<td><%= i.packagetype %></td> 
			
			<% @count=@count+1 %>
		</tr>
	<% end %>	
	<% end %>
</table>

app/views/workdesk/used_pin.html.erb
<label class="heading_lable">Used Pins</label>
<% @used_count=1 %>
<table class="table table-hover" >
	<tr>
		<td><b>Serial no</b></td>
		<td><b>Joining pin</b></td>
		<td><b>package</b></td>
		
	</tr>

	<% for i in @pins %>
	<% if i.frenchisename == current_user.username and i.used == true %>
		<tr>
			<td><b><%= @used_count %></b>
			</td><td><%= i.jpin %></td>
			<td><%= i.packagetype %></td> 
		</tr>
			<% @used_count=@used_count+1 %>
		</tr>
	<% end %>	
	<% end %>
</table>