config/routes.rb
AddLive::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :clients
  resources :client
  resources :ads
  resources :pin
  devise_for :users
  resources :clicks
  
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  get "users/new"

  root :to => 'staticpage#index'
  match '/vision', to: 'staticpage#vision'
  match '/about', to: 'staticpage#about'
  match '/career', to: 'staticpage#career'
  match '/rewards', to: 'staticpage#faq'
  match '/plan', to: 'staticpage#plan'
  match '/support', to: 'staticpage#support'
  match '/whyaddlive', to: 'staticpage#whyaddlive'
  match '/statistics', to: 'staticpage#statistics'
  match '/ads/index', to: 'ads#index'
  match '/workdesk/ads_list', to: 'workdesk#ads_list'
  match '/ads/:id', to: 'ads#show'
  match '/searchyourneed', to: 'staticpage#need'
  match '/signup', to: 'users#new'
  match '/Workdesk', to: 'Workdesk#index'
  match '/client', to: 'client#index'
  match '/check', to: 'ads#check'
  match '/fail', to: 'ads#fail'
  match '/success', to: 'ads#success'
  match '/career_page/:id', to: 'staticpage#career_page'
  match '/full_ads/:id', to: 'client#full_ads'
  match '/workdesk/create_request', to: 'workdesk#create_request'
  match 'workdesk/paid_history', to: 'workdesk#paid_history'
  match '/users', to: 'users#edit'
  match '/update', to: 'users#update'
  match '/legal', to: 'staticpage#legal'
  

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
  validates_uniqueness_of :username
  # attr_accessible :title, :body
  attr_accessor :login

   def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value ", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/models/ads.rb
class Ads < ActiveRecord::Base
	belongs_to :client
  attr_accessible :amount, :ans, :client_id, :que, :totalclicks, :usedclicks, :orgname, :category, :photo, :Active, :Imageslide, :city
   attr_accessor :photo
   has_attached_file :photo
end

app/models/career.rb
class Career < ActiveRecord::Base
  attr_accessible :address, :company, :contactno, :contactperson, :eligbility, :jobprofile,:remark
end

app/models/clicks.rb
class Clicks < ActiveRecord::Base
  attr_accessible :ads_id, :ans, :user_id
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :adss
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :username, :contactno, :address, :city, :category, :adscount, :fname, :lname,:encrypted_password,:state, :pincode
  # attr_accessible :title, :body
  validates_uniqueness_of :username
  # attr_accessible :title, :body
  attr_accessor :login

   def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value ", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/models/need.rb
class Need < ActiveRecord::Base
  attr_accessible :address, :category, :city, :contactno, :orgname

 end

app/models/paid_req_points.rb
class PaidReqPoints < ActiveRecord::Base
  attr_accessible :PaidDate, :paid, :points, :user_id, :tds, :admincharge
  
  scope :unpaid, where(:paid => false)
  scope :paid, where(:paid => true)
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	
  attr_accessible :amount, :jpin, :used, :user_id, :packagetype, :registration_type, :frenchisename
  validates :jpin, :presence => true, :uniqueness => true, :length => { :minimum => 15, :maximum => 15, }

  scope :unused, where(:used => false)
  scope :used, where(:used => true)
  scope :silver, where(:packagetype => "Silver")
  scope :gold, where(:packagetype => "Gold")
  scope :platinum, where(:packagetype => "Platinum")
end

app/models/points.rb
class Points < ActiveRecord::Base
  belongs_to :user
  attr_accessible :points, :user_id, :Ads_id, :Referal
  attr_accessor :Ads_id

end

app/models/user.rb
class User < ActiveRecord::Base
  scope :frenchise, where(:frenchise =>true)
  has_one :pin
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
attr_accessible :email, :password, :password_confirmation,:fname,:lname,:registration_type,:state,:sponserID,:jpin,:contactno,:address,:city,:pincode,:nameofbank,:accountno,:ifscno,:panno,:username,:login,:packagetype,:frenchise

validates_uniqueness_of :username
  # attr_accessible :title, :body
  attr_accessor :login

   def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value ", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
	before_filter :authenticate_user!
	
		$do_not_open_without_link=1
	def index
		@ads= Ads.all
		if $do_not_open_without_link==1
			$ads1=Ads.find(params[:id])
		else
			redirect_to '/Workdesk'
		end
		@chk_clicks=Clicks.where("user_id=?",current_user.id)
	end

	def new
		
	end


	def create
		
	end

	def check
		if $ads1.ans == params[:ans]
			Clicks.create(:user_id => current_user.id, :ads_id => $ads1.id, :ans => params[:ans])
			#@used_click_add=$ads1
			#@countused=$ads1.usedclicks
			$ads1.update_attributes(:usedclicks => $ads1.usedclicks+1)
			if current_user.packagetype == "Silver"
				@ads_success_point = 0.050
			elsif current_user.packagetype == "Gold"
				@ads_success_point = 0.075
			elsif current_user.packagetype == "Platinum"
				@ads_success_point = 0.100
			end
			Points.create(:user_id => current_user.id, :points => @ads_success_point, :Referal => false , :Ads_id => $ads1.id)

			redirect_to '/success'
		else
			redirect_to '/fail'
		end
	end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  
  end

  def delete

  end
  
  def edit
  	  	 @user= User.new  	  	 
  end

  def update
  	
  	@update_user =User.new(params[:user])
  	@id = current_user.id
  	@cuser = User.find(@id)

  	if @update_user.password == @update_user.password_confirmation
  		@cuser.update_attributes(:password => @update_user.password,:panno => @update_user.panno, :fname => @update_user.fname, :lname => @update_user.lname, :contactno => @update_user.contactno, :email => @update_user.email, :address => @update_user.address, :city => @update_user.city, :pincode => @update_user.pincode, :nameofbank => @update_user.nameofbank, :ifscno => @update_user.ifscno, :accountno => @update_user.accountno)
  	end	

  end



end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/career_helper.rb
module CareerHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
	
	def ppt_path(file)
  		File.join('/download', file).to_s
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workdesk_helper.rb
module WorkdeskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title>Add-Live | <%= yield(:title)%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 
 <%= favicon_link_tag 'fevicon1.jpg' %>
</head>

<body>
	
	    <div class="container">
	    	
	       	<div class="logoc">
	       		<div class="span3">
		      		<%= link_to image_tag("add1.png"), root_path, id: "logo" %>
		    	</div>
		    	<div class="home_image span2">
		    		<%= image_tag("home_image1.png") %>
		    		<%= image_tag("home_image2.png") %>
		    		<%= image_tag("home_image3.png") %>
		    		<%= image_tag("home_image4.png") %>
		    		<%= image_tag("home_image5.png") %>
		    		<%= image_tag("home_image6.png") %>
		    	</div>

		    	   	<div class="span2 offset3">

					  <% if user_signed_in? %>
						<b>
					    	Welcome, <%= current_user.fname %> 
						</b>
					    <div class="header_sign_out">
					    	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
						</div>
					  <% else %>
					  	<% if client_signed_in? %>
						<b>
					    	Welcome, <%= current_client.fname %> 
						</b>
					    <div class="header_sign_out">
					    	<%= link_to "Sign out", destroy_client_session_path, :method => :delete %>
						</div>
					  <% else %>
					    <b>Welcome, Guest</b>
					    <% end %> <p>
					  <% end %>
						<%= Time.now.strftime("%d-%m-%Y") %>
						
					</div>
	    	 </div>

		    </div>
		    
		<div class="container">
		   	<% flash.each do |name,msg| %>
		    	<% content_tag :div ,msg,:id=>"flash_#{name}" %>
		    	<p class="alert"><%= notice %>
 				<%= alert %></p>
		    <% end %>
 			
		</div>
	  
	<div class="container">
	  <div class="navbar sec_nav navbar-inverse">
	  	<div class="navbar-inner">
		    
	      	<ul class="nav">
	      		<li> <%= link_to "Why Add-live", '/whyaddlive', id: "nv_hover" %> </li>
	      		<li class="divider-vertical"></li>
	      		<li> <%= link_to "Vision", '/vision', id: "nv_hover" %> </li>
	      		<li class="divider-vertical"></li>
	      		<li> <%= link_to "AboutUs", '/about', id: "nv_hover" %> </li>
	      		<li class="divider-vertical"></li>
	      		<li> <%= link_to "Plan", '/plan', id: "nv_hover" %> </li>
	      		<li class="divider-vertical"></li>
	      		<li> <%= link_to "Support", '/support', id: "nv_hover" %> </li>
	      		<li class="divider-vertical"></li>
	      		<li> <%= link_to "Career", '/career', id: "nv_hover" %> </li>
	      		<li class="divider-vertical"></li>
	      		<li> <%= link_to "Reward", '/rewards', id: "nv_hover" %> </li>
	      		<li class="divider-vertical"></li>
	      		<li> <%= link_to "Search your need ", '/searchyourneed', id: "nv_hover" %> <div class="new"><%= image_tag "New-08-june.gif" %></div></li>
	      		<li class="divider-vertical"></li>
	      		<li> <%= link_to "Legal", '/legal', id: "nv_hover" %> </li>
	      	</ul>
		    
	    </div>
	  </div>
	</div>
	<div class="container">
      <%= yield %>
     	<footer>
    		<hr></hr>
    		<div class="main_footer">
	    	<p align="center">
	    		Enquiry for Frenchiese mail us at :<font color="blue"><b>support@add-live.com</b></font>
	    	</p>
	    	<p align="center">
	    		Copyright 2012 Add-live
	    		
	    	</p>

	    </div>
	    
    	</footer>
    </div>
</body>
<script>

$(function() {
    $('.home_image').cycle();
});

</script>
</html>